sonar.projectName=MULTICAS TrackOn
sonar.projectVersion=0.1.0
sonar.sourceEncoding=UTF-8
sonar.projectKey=NuppyOz_TrackOn
sonar.organization=nuppyoz

sonar.sources=apps/api/src,apps/web/src
sonar.tests=apps/api/test,apps/web/test
sonar.test.inclusions=apps/api/test/**/*.test.ts,apps/web/test/**/*.test.ts,apps/web/test/**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/dist/**,apps/api/src/generated/prisma/**,**/*.d.ts,**/coverage/**,**/*.png,**/*.jpg,**/*.jpeg,**/*.webp,**/*.gif,**/*.ico,**/*.svg
sonar.cpd.exclusions=apps/api/test/**/*,apps/web/test/**/*
sonar.javascript.lcov.reportPaths=apps/api/coverage/lcov.info,apps/web/coverage/lcov.info
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
